[workspace]
members = ["crates/*"]

default-members = ["crates/flox"]

[patch.crates-io]
bpaf = { git = "https://github.com/ysndr/bpaf", branch = "error/more-suggestions" }
runix = { git = "https://github.com/flox/runix", rev = "3dd27a66fae910db6d4da71a4aeea1810310e239" }
