name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  FLOX_SUBSTITUTER: "s3://flox-store"

jobs:

  build:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - package: flox
          - package: flox-bash
          - package: nix-editor

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install flox
      uses: flox/install-flox-action@main
      with:
        github-access-token: ${{ secrets.NIX_GIT_TOKEN }}
        substituter: ${{ env.FLOX_SUBSTITUTER }}
        substituter-key: ${{ secrets.FLOX_STORE_PUBLIC_NIX_SECRET_KEY }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build
      run: flox nix build .#${{ matrix.package }} -L --print-out-paths

    - name: Cache
      run: flox nix copy --to "${{ env.FLOX_SUBSTITUTER }}" '.#${{ matrix.package }}^*'

    - name: Test
      if: ${{ matrix.package == 'flox' }}
      run: |
        flox run flox-tests -- -- --flox $(realpath ./result/bin/flox)
