name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - package: flox
          - package: flox-bash
          - package: nix-editor

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install flox
      uses: flox/install-flox-action@main
      with:
        github-access-token: ${{ secrets.NIX_GIT_TOKEN }}

    - name: Build
      run: flox build ${{ matrix.package }} -L

  test-flox:
    name: Test flox
    runs-on: ubuntu-latest

    # TODO: add a dependency on build part once we have some caching

    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

      - name: GPG Signature Setup
        run: |
          git config --global gpg.format ssh;
          git config --global user.signingkey /home/runner/.ssh/id_rsa.pub;

    - name: Install flox
      uses: flox/install-flox-action@main
      with:
        github-access-token: ${{ secrets.NIX_GIT_TOKEN }}

    - name: Test
      run: flox run .#flox-tests -L
